language: node_js
node_js:
- '16'
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: KcCJUnQRFAPjHZSpdUt8ubWCblltmKK88UE+n55fHTBVfQUTI8zZC3rLkOZ/Rg8PcacD1JeCp/Q6k1JPSxxcb43S4MrUB+Mj75tUaDDg7LuKXVt9OGO1YmUcRliGNvcACtnBPaPajUKef2swFK9+6Kicqwdw84V8/0/MSqgVQp5a8Y8z3RlbdONvSs1G4qtoohM1hlTl69H6e79yhb8BPk5+MFC6+B2PkYP4zRLFWJoagzxS03jsF1DU5ax50slGCQScSVFiYC5CVtDPFgK7hrl5cL2BKbbt1NjfdSFVG/ME+ZQ+h1XgQelHr/UKwpTQtDOo96w+LOCXrerVTpI6/AffTzYY9LQH0cu4r9p1kbUuHQqvTrTqZl/6YkGeivJB3847ilAB2ikvxPfW84OnaoYDBJBCsW11rjo45b6VyfJE9WvwQbOHh/LPYXh55A6Ijws4K0f1U2R11dVSUjXjKhBJ5n4ZwqLqzCGvCoYtg6iSLl3O++asXGg2gqvv7u9l55v2rsbE4+JRF+raFdQrT+d6hOMvWtQYmiUFP5C9H8/VopnIpavMfQ2TpwRK0kbEzlgaQYj34zMUSeUC7SVdMZ+yrb0UoASCaaV5abO/DAAymQBSQML41PO9uTFafrJojY8mt32bTaiF7tuzFw4HaDSmE7SrnG69ThJejGfuIqE=
  app: auladevops-pipeline
  edge: true
